# Generated by Django 4.2.6 on 2024-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_category_name_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.FileField(null=True, upload_to='group/image'),
        ),
    ]
